### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by sr105-tm** [kraiskil/cmake_timestamp#1]
I realize that you probably intend this to be free as in public domain. Would you mind explicitly stating that in the readme? I'd like to use this with a commercial product, but I can't use it without the guarantee.

**Comment by kraiskil** [comment]
Sorry for not reacting faster, I completely missed the notification (and this repo is not one I check often).

Actually, at the time of writing this the local jurisdiction didn't recognize the concept of 'public domain' (I was told, IANAL). I'm not sure about what the current legislation says. Or how that applies to this code or the user... 

To circumvent all this, there are now licensing terms in place. In short: do whatever you want. If it breaks your computer you get to keep the pieces, but you can't blame me for it ;)
